apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2023-07-04T14:00:22Z"
  generation: 1
  labels:
    app: web
    label: catalin
  name: web
  namespace: catalin-flux-system
  resourceVersion: "51693357"
  uid: 3eb74bfd-5571-45a0-84e8-a329fc2f1713
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web
    spec:
      containers:
      - image: gcr.io/google-samples/hello-app:1.0
        imagePullPolicy: IfNotPresent
        name: hello-app
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
